In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [2]:
df = pd.read_csv("../data/raw/youtube_dataset.csv")

In [3]:
df.head()

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count,search_keyword,search_category,collected_at
0,r3I1_biJ5Rs,How OpenAI technology 'went rogue' | Global Ne...,The artificial intelligence giant OpenAI - mak...,2006-04-08T05:51:05Z,UC16niRr50-MSBwiO3YDb3RA,BBC News,25,"['bbc', 'bbc news', 'news', 'world news', 'bre...",PT9M43S,7128283600,338.0,140.0,https://i.ytimg.com/vi/r3I1_biJ5Rs/hqdefault.jpg,"Breaking news, live updates and in-depth analy...",GB,19900000,31890,technology news,Technology,2026-07-23 13:24:57
1,rIj7DnrshxY,"Tech News 2212 || Galaxy Unpacked, vivo S2, re...","Tech News 2212 || Galaxy Unpacked, vivo S2, re...",2015-11-12T05:14:19Z,UCb-xXZ7ltTvrh9C6DgB9H-Q,Prasadtechintelugu,28,"['prasadtechintelugu', 'prasad', 'techtelugu',...",PT8M47S,2188859182,8255.0,304.0,https://i.ytimg.com/vi/rIj7DnrshxY/hqdefault.jpg,"Technology , Smartphone Reviews , Unboxing Gad...",IN,5140000,5351,technology news,Technology,2026-07-23 13:24:57
2,pKsEFQgpe-o,"Nvidia Rolls Out New Chips, WBD Deal In Limbo ...",Bloomberg's Ed Ludlow breaks down Nvidia's lat...,2016-09-01T21:38:32Z,UCrM7B7SL_g1edFOnmj-SDKg,Bloomberg Tech,25,"['Advisors Capital Management LLC', 'Bessemer ...",PT49M8S,177869185,139.0,8.0,https://i.ytimg.com/vi/pKsEFQgpe-o/hqdefault.jpg,Welcome to the Bloomberg Tech YouTube channel....,NaN,732000,13916,technology news,Technology,2026-07-23 13:24:57
3,qnnXBakpLoc,"Tech News 2211 || Xiaomi, Redmi Note 17, Pixel...","Tech News 2211 || Xiaomi, Redmi Note 17, Pixel...",2015-11-12T05:14:19Z,UCb-xXZ7ltTvrh9C6DgB9H-Q,Prasadtechintelugu,28,"['prasadtechintelugu', 'prasad', 'techtelugu',...",PT8M18S,2188859182,9297.0,265.0,https://i.ytimg.com/vi/qnnXBakpLoc/hqdefault.jpg,"Technology , Smartphone Reviews , Unboxing Gad...",IN,5140000,5351,technology news,Technology,2026-07-23 13:24:57
4,2JgJ1MRhntg,Microsoft in the race to build the ultimate su...,Computing giant Microsoft has spent 20 years p...,2006-04-08T05:51:05Z,UC16niRr50-MSBwiO3YDb3RA,BBC News,25,"['bbc', 'bbc news', 'news', 'world news', 'bre...",PT5M33S,7128283600,2212.0,341.0,https://i.ytimg.com/vi/2JgJ1MRhntg/hqdefault.jpg,"Breaking news, live updates and in-depth analy...",GB,19900000,31890,technology news,Technology,2026-07-23 13:24:57

In [4]:
df.shape

(2061, 20)

In [7]:
df.columns

Index(['video_id', 'title', 'description', 'published_at', 'channel_id',
       'channel_title', 'category_id', 'tags', 'duration', 'view_count',
       'like_count', 'comment_count', 'thumbnail_url', 'channel_description',
       'country', 'subscriber_count', 'video_count', 'search_keyword',
       'search_category', 'collected_at'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2061 entries, 0 to 2060
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             2061 non-null   str
 1   title                2061 non-null   str
 2   description          1846 non-null   str
 3   published_at         2061 non-null   str
 4   channel_id           2061 non-null   str
 5   channel_title        2061 non-null   str
 6   category_id          2061 non-null   int64
 7   tags                 1543 non-null   str
 8   duration             2061 non-null   str
 9   view_count           2061 non-null   int64
 10  like_count           2009 non-null   float64
 11  comment_count        2041 non-null   float64
 12  thumbnail_url        2061 non-null   str
 13  channel_description  2024 non-null   str
 14  country              1828 non-null   str
 15  subscriber_count     2061 non-null   int64
 16  video_count          2061 non-null   int64
 17  search_keyword       2061 non-null   str
 18  search_category      2061 non-null   str
 19  collected_at         2061 non-null   str
dtypes: float64(2), int64(4), str(14)
memory usage: 5.4 MB

In [9]:
df.isnull().sum()

video_id                 0
title                    0
description            215
published_at             0
channel_id               0
channel_title            0
category_id              0
tags                   518
duration                 0
view_count               0
like_count              52
comment_count           20
thumbnail_url            0
channel_description     37
country                233
subscriber_count         0
video_count              0
search_keyword           0
search_category          0
collected_at             0
dtype: int64

In [11]:
df.describe()

,category_id,view_count,like_count,comment_count,subscriber_count,video_count
count,2061.000000,2.061000e+03,2.009000e+03,2041.000000,2.061000e+03,2061.000000
mean,25.791363,9.295211e+08,7.805003e+04,1597.521803,3.289767e+06,5718.688986
std,2.915333,4.125027e+09,2.967967e+05,11411.675273,1.259385e+07,32218.047716
min,1.000000,3.600000e+03,1.000000e+00,0.000000,2.200000e+01,1.000000
25%,25.000000,1.544134e+07,2.321000e+03,48.000000,9.640000e+04,281.000000
50%,27.000000,1.006207e+08,1.063700e+04,216.000000,6.880000e+05,826.000000
75%,27.000000,5.524178e+08,4.505700e+04,793.000000,2.940000e+06,2138.000000
max,29.000000,1.342652e+11,6.215914e+06,412557.000000,5.090000e+08,665951.000000

In [12]:
(df.isnull().sum() / len(df)) * 100

video_id                0.000000
title                   0.000000
description            10.431829
published_at            0.000000
channel_id              0.000000
channel_title           0.000000
category_id             0.000000
tags                   25.133430
duration                0.000000
view_count              0.000000
like_count              2.523047
comment_count           0.970403
thumbnail_url           0.000000
channel_description     1.795245
country                11.305192
subscriber_count        0.000000
video_count             0.000000
search_keyword          0.000000
search_category         0.000000
collected_at            0.000000
dtype: float64

In [13]:
df.duplicated().sum()

np.int64(0)

In [14]:
df.drop_duplicates(inplace=True)

In [16]:
for col in df.columns:
    print(col, df[col].nunique())

video_id 94
title 93
description 90
published_at 60
channel_id 60
channel_title 60
category_id 5
tags 72
duration 89
view_count 60
like_count 91
comment_count 86
thumbnail_url 94
channel_description 57
country 6
subscriber_count 60
video_count 58

In [17]:
df.dtypes

video_id                   str
title                      str
description                str
published_at               str
channel_id                 str
channel_title              str
category_id              int64
tags                       str
duration                   str
view_count               int64
like_count             float64
comment_count          float64
thumbnail_url              str
channel_description        str
country                    str
subscriber_count         int64
video_count              int64
dtype: object

In [19]:
df.describe(include="all")

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count
count,94,94,90,94,94,94,94.000000,72,94,9.400000e+01,9.100000e+01,93.000000,94,91,87,9.400000e+01,94.000000
unique,94,93,90,60,60,60,NaN,72,89,NaN,NaN,NaN,94,57,6,NaN,NaN
top,sxQnkMfp_6M,Python Full Course for Beginners,హైదరాబాద్‌ KBR పార్క్‌లో భారీ కొండచిలువ | Huge...,2014-12-16T21:18:48Z,UC8butISFwT-Wl7EV0hUK0BQ,freeCodeCamp.org,NaN,"['Huge Python at Hyderabad KBR Park', 'Hyderab...",PT16S,NaN,NaN,NaN,https://i.ytimg.com/vi/sxQnkMfp_6M/hqdefault.jpg,"Learn math, programming, and computer science ...",US,NaN,NaN
freq,1,2,1,8,8,8,NaN,1,3,NaN,NaN,NaN,1,8,52,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,26.797872,NaN,NaN,3.810969e+08,8.491480e+04,3119.612903,NaN,NaN,NaN,3.275544e+06,7872.670213
std,NaN,NaN,NaN,NaN,NaN,NaN,1.249342,NaN,NaN,5.816902e+08,1.967828e+05,10331.069412,NaN,NaN,NaN,3.851716e+06,40521.674150
min,NaN,NaN,NaN,NaN,NaN,NaN,22.000000,NaN,NaN,2.551120e+05,6.800000e+01,0.000000,NaN,NaN,NaN,2.930000e+03,39.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,1.873231e+07,3.148000e+03,53.000000,NaN,NaN,NaN,1.382500e+05,240.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,1.629271e+08,2.557600e+04,299.000000,NaN,NaN,NaN,1.510000e+06,1014.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,5.616530e+08,7.128200e+04,1344.000000,NaN,NaN,NaN,5.110000e+06,2875.250000
max,NaN,NaN,NaN,NaN,NaN,NaN,28.000000,NaN,NaN,3.787895e+09,1.261583e+06,62840.000000,NaN,NaN,NaN,1.320000e+07,387957.000000