In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use("ggplot")

In [2]:
df = pd.read_csv("../data/raw/youtube_dataset.csv")

In [3]:
df.head()

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count,search_keyword,search_category,collected_at
0,r3I1_biJ5Rs,How OpenAI technology 'went rogue' | Global Ne...,The artificial intelligence giant OpenAI - mak...,2006-04-08T05:51:05Z,UC16niRr50-MSBwiO3YDb3RA,BBC News,25,"['bbc', 'bbc news', 'news', 'world news', 'bre...",PT9M43S,7128283600,338.0,140.0,https://i.ytimg.com/vi/r3I1_biJ5Rs/hqdefault.jpg,"Breaking news, live updates and in-depth analy...",GB,19900000,31890,technology news,Technology,2026-07-23 13:24:57
1,rIj7DnrshxY,"Tech News 2212 || Galaxy Unpacked, vivo S2, re...","Tech News 2212 || Galaxy Unpacked, vivo S2, re...",2015-11-12T05:14:19Z,UCb-xXZ7ltTvrh9C6DgB9H-Q,Prasadtechintelugu,28,"['prasadtechintelugu', 'prasad', 'techtelugu',...",PT8M47S,2188859182,8255.0,304.0,https://i.ytimg.com/vi/rIj7DnrshxY/hqdefault.jpg,"Technology , Smartphone Reviews , Unboxing Gad...",IN,5140000,5351,technology news,Technology,2026-07-23 13:24:57
2,pKsEFQgpe-o,"Nvidia Rolls Out New Chips, WBD Deal In Limbo ...",Bloomberg's Ed Ludlow breaks down Nvidia's lat...,2016-09-01T21:38:32Z,UCrM7B7SL_g1edFOnmj-SDKg,Bloomberg Tech,25,"['Advisors Capital Management LLC', 'Bessemer ...",PT49M8S,177869185,139.0,8.0,https://i.ytimg.com/vi/pKsEFQgpe-o/hqdefault.jpg,Welcome to the Bloomberg Tech YouTube channel....,NaN,732000,13916,technology news,Technology,2026-07-23 13:24:57
3,qnnXBakpLoc,"Tech News 2211 || Xiaomi, Redmi Note 17, Pixel...","Tech News 2211 || Xiaomi, Redmi Note 17, Pixel...",2015-11-12T05:14:19Z,UCb-xXZ7ltTvrh9C6DgB9H-Q,Prasadtechintelugu,28,"['prasadtechintelugu', 'prasad', 'techtelugu',...",PT8M18S,2188859182,9297.0,265.0,https://i.ytimg.com/vi/qnnXBakpLoc/hqdefault.jpg,"Technology , Smartphone Reviews , Unboxing Gad...",IN,5140000,5351,technology news,Technology,2026-07-23 13:24:57
4,2JgJ1MRhntg,Microsoft in the race to build the ultimate su...,Computing giant Microsoft has spent 20 years p...,2006-04-08T05:51:05Z,UC16niRr50-MSBwiO3YDb3RA,BBC News,25,"['bbc', 'bbc news', 'news', 'world news', 'bre...",PT5M33S,7128283600,2212.0,341.0,https://i.ytimg.com/vi/2JgJ1MRhntg/hqdefault.jpg,"Breaking news, live updates and in-depth analy...",GB,19900000,31890,technology news,Technology,2026-07-23 13:24:57

In [4]:
df.tail()

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count,search_keyword,search_category,collected_at
2224,aNHZTsDbqiM,Future of the Creator Economy: The Rise of Exp...,NaN,2014-01-11T19:26:14Z,UC4CmCMytZWM275JbzvyObUQ,Joel Marlinarson,24,NaN,PT30S,34312,30.0,1.0,https://i.ytimg.com/vi/aNHZTsDbqiM/hqdefault.jpg,"I'm Joel Marlinarson - content creator, social...",GB,548,33,creator economy,Content Creation,2026-07-24 17:19:40
2225,ZD3DctHbz-0,Reality of Content Creator's Economy!,Video Editing Course (Recorded): https://learn...,2023-03-10T09:42:50.184081Z,UC0_36RirUPzzsFWaLJ-yfGg,The Social Brains,27,"['social brains', 'the social brains', 'digraj...",PT12M41S,48888477,9921.0,1026.0,https://i.ytimg.com/vi/ZD3DctHbz-0/hqdefault.jpg,"Hello Everyone, Welcome to The Social Brains!\...",IN,729000,254,creator economy,Content Creation,2026-07-24 17:19:40
2226,Li-6QMs9_G4,The creator economy is dying thanks to AI,Previously we talked about the death of the pe...,2016-03-14T22:22:20Z,UCWXYDYv5STLk-zoxMP2I1Lw,Dan Koe,27,"['self improvement', 'mindset', 'personal deve...",PT27M58S,48361746,7348.0,466.0,https://i.ytimg.com/vi/Li-6QMs9_G4/hqdefault.jpg,"If you want harsh truths, read my letters.\n",US,1400000,247,creator economy,Content Creation,2026-07-24 17:19:40
2227,19ApreTs_r8,The Future of The Creator Economy,"In today's video, I'm sharing a recent press c...",2007-10-06T18:54:42Z,UCctXZhXmG-kf3tlIXgVZUlw,GaryVee,24,"['Gary Vaynerchuk', 'gary vee', 'gary vaynerch...",PT13M29S,688596651,882.0,50.0,https://i.ytimg.com/vi/19ApreTs_r8/hqdefault.jpg,Gary Vaynerchuk is a serial entrepreneur and s...,US,4840000,7332,creator economy,Content Creation,2026-07-24 17:19:40
2228,7bdRo3hoTEA,9 In 10 Indian Creators Struggle To Earn Onlin...,A new look at India’s creator economy shows th...,2016-05-19T12:55:08Z,UC_gUM8rL-Lrg6O3adPW9K1g,WION,25,"['Indian creator economy', 'influencers India'...",PT1M52S,6898563177,319.0,85.0,https://i.ytimg.com/vi/7bdRo3hoTEA/hqdefault.jpg,"WION -The World is One News, examines global i...",IN,10500000,293506,creator economy,Content Creation,2026-07-24 17:19:40

In [5]:
df.shape

(2229, 20)

In [6]:
df.columns

Index(['video_id', 'title', 'description', 'published_at', 'channel_id',
       'channel_title', 'category_id', 'tags', 'duration', 'view_count',
       'like_count', 'comment_count', 'thumbnail_url', 'channel_description',
       'country', 'subscriber_count', 'video_count', 'search_keyword',
       'search_category', 'collected_at'],
      dtype='str')

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2229 entries, 0 to 2228
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   video_id             2229 non-null   str
 1   title                2229 non-null   str
 2   description          1990 non-null   str
 3   published_at         2229 non-null   str
 4   channel_id           2229 non-null   str
 5   channel_title        2229 non-null   str
 6   category_id          2229 non-null   int64
 7   tags                 1663 non-null   str
 8   duration             2229 non-null   str
 9   view_count           2229 non-null   int64
 10  like_count           2158 non-null   float64
 11  comment_count        2209 non-null   float64
 12  thumbnail_url        2229 non-null   str
 13  channel_description  2189 non-null   str
 14  country              1972 non-null   str
 15  subscriber_count     2229 non-null   int64
 16  video_count          2229 non-null   int64
 17  search_keyword       2229 non-null   str
 18  search_category      2229 non-null   str
 19  collected_at         2229 non-null   str
dtypes: float64(2), int64(4), str(14)
memory usage: 5.8 MB

In [8]:
df.isnull().sum()

video_id                 0
title                    0
description            239
published_at             0
channel_id               0
channel_title            0
category_id              0
tags                   566
duration                 0
view_count               0
like_count              71
comment_count           20
thumbnail_url            0
channel_description     40
country                257
subscriber_count         0
video_count              0
search_keyword           0
search_category          0
collected_at             0
dtype: int64

In [9]:
(df.isnull().sum() / len(df)) * 100

video_id                0.000000
title                   0.000000
description            10.722297
published_at            0.000000
channel_id              0.000000
channel_title           0.000000
category_id             0.000000
tags                   25.392553
duration                0.000000
view_count              0.000000
like_count              3.185285
comment_count           0.897263
thumbnail_url           0.000000
channel_description     1.794527
country                11.529834
subscriber_count        0.000000
video_count             0.000000
search_keyword          0.000000
search_category         0.000000
collected_at            0.000000
dtype: float64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop_duplicates(inplace=True)

In [12]:
for col in df.columns:
    print(col, df[col].nunique())

video_id 2229
title 2218
description 1964
published_at 1423
channel_id 1423
channel_title 1423
category_id 13
tags 1581
duration 1170
view_count 1442
like_count 2048
comment_count 1056
thumbnail_url 2229
channel_description 1381
country 45
subscriber_count 1091
video_count 999
search_keyword 116
search_category 14
collected_at 116

In [13]:
df.describe(include="all")

,video_id,title,description,published_at,channel_id,channel_title,category_id,tags,duration,view_count,like_count,comment_count,thumbnail_url,channel_description,country,subscriber_count,video_count,search_keyword,search_category,collected_at
count,2229,2229,1990,2229,2229,2229,2229.000000,1663,2229,2.229000e+03,2.158000e+03,2209.000000,2229,2189,1972,2.229000e+03,2229.000000,2229,2229,2229
unique,2229,2218,1964,1423,1423,1423,NaN,1581,1170,NaN,NaN,NaN,2229,1381,45,NaN,NaN,116,14,116
top,r3I1_biJ5Rs,🔥Top Best Useful Gadgets In The World | Amazon...,*TELEGRAM LINK 📌* \nhttps://t.me/Shivani_Palle...,2009-10-29T07:21:23Z,UCsvqVGtbbyHaMoevxPAq9Fg,Simplilearn,NaN,"['warikoo', 'ankur warikoo', 'Ankur Warikoo mo...",PT1M,NaN,NaN,NaN,https://i.ytimg.com/vi/r3I1_biJ5Rs/hqdefault.jpg,Simplilearn is the world’s leading online trai...,IN,NaN,NaN,technology news,Digital Marketing,2026-07-23 13:24:57
freq,1,2,7,40,40,40,NaN,8,55,NaN,NaN,NaN,1,40,932,NaN,NaN,20,199,20
mean,NaN,NaN,NaN,NaN,NaN,NaN,25.598923,NaN,NaN,8.810023e+08,7.543361e+04,1575.276596,NaN,NaN,NaN,3.131547e+06,5531.970390,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,3.475578,NaN,NaN,3.983418e+09,2.872278e+05,11010.302601,NaN,NaN,NaN,1.219601e+07,31666.481148,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,3.600000e+03,1.000000e+00,0.000000,NaN,NaN,NaN,2.200000e+01,1.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,24.000000,NaN,NaN,1.394165e+07,2.390500e+03,50.000000,NaN,NaN,NaN,8.680000e+04,257.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,8.542475e+07,1.064850e+04,222.000000,NaN,NaN,NaN,6.300000e+05,764.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,27.000000,NaN,NaN,4.691659e+08,4.483800e+04,794.000000,NaN,NaN,NaN,2.820000e+06,1956.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,29.000000,NaN,NaN,1.342652e+11,6.215914e+06,412557.000000,NaN,NaN,NaN,5.090000e+08,665951.000000,NaN,NaN,NaN

In [14]:
print(df.columns.tolist())

['video_id', 'title', 'description', 'published_at', 'channel_id', 'channel_title', 'category_id', 'tags', 'duration', 'view_count', 'like_count', 'comment_count', 'thumbnail_url', 'channel_description', 'country', 'subscriber_count', 'video_count', 'search_keyword', 'search_category', 'collected_at']

**Negative Values**

In [15]:
numeric_cols = [
    "view_count",
    "like_count",
    "comment_count",
    "subscriber_count",
]

(df[numeric_cols] < 0).sum()

view_count          0
like_count          0
comment_count       0
subscriber_count    0
dtype: int64

Zero Values

In [16]:
(df[numeric_cols] == 0).sum()

view_count           0
like_count           0
comment_count       46
subscriber_count     0
dtype: int64